export const ERRORS = {
  AUTH: {
    PROVIDE_TOKEN: 'AUTH_PROVIDE_TOKEN'
  },
  USER: {
    NOT_FOUND: 'USER_NOT_FOUND',
    INCORRECT_PASSWORD_OR_EMAIL: 'INCORRECT_PASSWORD_OR_EMAIL',
    NOT_ALLOW: 'USER_NOT_ALLOW'
  },
  COMPANY: {
    CNPJ_ALREADY_EXIST: 'COMPANY_CNPJ_ALREADY_EXIST',
    NOT_FOUND: 'COMPANY_NOT_FOUND'
  }
}